CREATE DATABASE hbo; 

USE hbo;

CREATE TABLE user (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(16) NOT NULL,
    password VARCHAR(60) NOT NULL,
    fullname VARCHAR(100) NOT NULL
);

CREATE TABLE movies (
    id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    genero VARCHAR(120) NOT NULL
    
);
ALTER TABLE movies 
    MODIFY title VARCHAR(120) NOT NULL,
    MODIFY url VARCHAR(255) NOT NULL,
   ADD COLUMN description TEXT;